# ============================================================
# Pipeline Parameters (params.yaml)
# ============================================================

# -------------------- Inputs --------------------
samplesheet: "./refs/samplesheet.csv"

# -------------------- Reference Base (informational) --------------------
ref_base: "/fs04/vh83/pipeline_reference"

# -------------------- Core References --------------------
reference: "/fs04/vh83/pipeline_reference/genomes/hg38/Homo_sapiens_assembly38.fasta"
reference_fai: "/fs04/vh83/pipeline_reference/genomes/hg38/Homo_sapiens_assembly38.fasta.fai"
bed: "/fs04/vh83/pipeline_reference/panels/Agilent_exomes/SureSelectXTHS2_V8_hg38/S33266436_Padded_namefixed_filtered.bed"

# -------------------- Outputs --------------------
outdir: "result"

# -------------------- VarDict --------------------
min_af: 0.05

# -------------------- CNVkit --------------------
cnvkit_genemetrics_threshold: 0.4
cnvkit_genemetrics_min_probes: 1

# -------------------- VEP --------------------
# These params kinda have to fit what's inside the vep_cache_dir I think, as VEP the tool looks for: <dir_cache>/<species>/<version>_<assembly>

vep_species: "homo_sapiens"
vep_version: "115"
vep_assembly: "GRCh38"
vep_cache_dir: "/fs04/vh83/pipeline_reference/annotations/vep_cache/115/RefSeq"


# -------------------- SnpEff / Annotation --------------------
# where your refs live on the host
refs_dir: "/fs04/vh83/pipeline_reference/"
mane_dir: "/fs04/vh83/pipeline_reference/annotations/snpeff_cache/h38/MANE/1.2/"
clinvar_vcf: "/fs04/vh83/pipeline_reference/annotations/clinvar/20250928/clinvar_20250928.vcf.gz"

# Which ClinVar INFO fields to keep
clinvar_info: "CLNSIG,CLNREVSTAT,CLNDN,CLNVC,ALLELEID,CLNVCSO,RS"

snpeff_genome: "GRCh38.99"
snpeff_data: "/snpeff_data"

# -------------------- pyTMB --------------------
pytmb_eff_size: 33280000
pytmb_annot: "snpeff"
pytmb_db_config: "/fs04/vh83/pipeline_reference/annotations/pytmb_settings/snpeff.yml"
pytmb_var_config: "/fs04/vh83/pipeline_reference/annotations/pytmb_settings/vardict.yml"
pytmb_vaf: 0.05
pytmb_min_depth: 20
pytmb_min_alt: 2
pytmb_filter_syn: true
pytmb_filter_nc: true
pytmb_filter_lq: true

# -------------------- Polysolver --------------------
polysolver_race: "Unknown"
polysolver_build: "hg38"
polysolver_emit_vcf: 0
polysolver_fastqtype: "STDFQ"
polysolver_insertcalc: 0

# -------------------- MultiQC --------------------
multiqc_extra_args: ""
